import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Changeblock",
  description: "Generated by changeblock",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-background `}>
        <Providers>
          <div className="flex  w-full h-screen  p-[1rem] max-h-screen   ">
            <Sidebar />
            <div className=" px-[1rem] relative  max-h-full bg-background w-full h-full flex flex-col gap-[2rem]  ">
              {children}
            </div>
          </div>{" "}
        </Providers>
      </body>
    </html>
  );
}
